### PR TITLE
binary package validation (via renv)

### LINKED ISSUE #712: test-load installed binary packages
R package binaries are not loaded during installation; missing or incompatible system libraries are not detected until the package is loaded at runtime.

We can see this problem with the `rjags` R package, which depends upon the `jags` system library.

Given this `Dockerfile.pkg-config`, a binary of `rjags` installs successfully, but then fails to load.

```dockerfile
FROM rstudio/r-base:4.3-jammy

RUN apt-get update && apt-get -y install pkg-config

ARG REPOSITORY=https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
RUN R -s -e "install.packages('rjags', repos=c(CRAN='${REPOSITORY}'))" && R -s -e "cat('POST-INSTALL:\n');library(rjags)"
```

Building:

```bash
docker build --progress=plain \
    --build-arg REPOSITORY=https://packagemanager.rstudio.com/cran/__linux__/jammy/latest \
    -f Dockerfile.pkg-config .
```

The output includes:

```
....
#6 2.816 * installing *binary* package ‘rjags’ ...
#6 2.822 * DONE (rjags)
#6 2.836
#6 2.836 The downloaded source packages are in
#6 2.836 	‘/tmp/RtmpOQfoTU/downloaded_packages’
#6 2.836 Updating HTML index of packages in '.Library'
#6 2.838 Making 'packages.html' ... done
#6 3.019 POST-INSTALL:
#6 3.026 Loading required package: coda
#6 3.064 Error: package or namespace load failed for ‘rjags’:
#6 3.064  .onLoad failed in loadNamespace() for 'rjags', details:
#6 3.064   call: dyn.load(file, DLLpath = DLLpath, ...)
#6 3.064   error: unable to load shared object '/opt/R/4.3.0/lib/R/library/rjags/libs/rjags.so':
#6 3.064   libjags.so.4: cannot open shared object file: No such file or directory
#6 3.064 Execution halted
```

This shows that library-load issues are not detected during installation when using binary packages.

### PR DESCRIPTION
**Pull request by aronatkins**
Loads binary packages at install time, which traps some environment compatibility problems. The package is removed from the packrat library and never reaches the packrat cache.

Fixes #712

The following Dockerfile examples show failures occurring at restore-time; the "runtime" script.R is never executed.

This first example shows how an install-time package load can identify missing system dependencies.

<details>
<summary>Dockerfile.packrat identifying missing (jags) system dependencies

```dockerfile
FROM rstudio/r-base:4.3-jammy AS base

RUN apt-get update && apt-get -y install pkg-config

ARG REPOSITORY=https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
RUN echo "options(repos = c(CRAN = '${REPOSITORY}'))" >> /opt/R/4.3.0/lib/R/etc/Rprofile.site

RUN R -s -e "install.packages('remotes')"

FROM base as setup

ARG PACKRAT_REF="aron-renv-binary-package-validation"
RUN R -s -e "remotes::install_github('rstudio/packrat', '${PACKRAT_REF}')"

FROM setup AS installation

RUN mkdir /content \
    && echo "library(rjags)" > /content/script.R \
    && echo "options(download.file.method = 'curl', download.file.extra = paste('-s -L -f -A ', shQuote(getOption('HTTPUserAgent'))))" > /content/.Rprofile

WORKDIR /content

ENV RENV_INSTALL_TEST_LOAD=True

RUN R -s -e "packrat::init(enter = FALSE, infer.dependencies = FALSE)"
# install by R of rjags into the packrat library..
RUN R -s -e "install.packages('rjags')"
RUN R -s -e "packrat::snapshot()"
RUN rm -rf packrat/lib* packrat/src
# installation by packrat of rjags into the packrat library.
RUN R -s -e "packrat::restore()"
RUN R -s -f "script.R"
```
</details>

```bash
docker build --progress=plain --no-cache-filter=setup -f Dockerfile.packrat .
```

```
 > [installation 7/8] RUN R -s -e "packrat::restore()":
#15 8.501 Loading required package: coda
#15 8.501 Error: package or namespace load failed for ‘rjags’:
#15 8.501  .onLoad failed in loadNamespace() for 'rjags', details:
#15 8.501   call: dyn.load(file, DLLpath = DLLpath, ...)
#15 8.501   error: unable to load shared object '/content/packrat/lib/x86_64-pc-linux-gnu/4.3.0/rjags/libs/rjags.so':
#15 8.501   libjags.so.4: cannot open shared object file: No such file or directory
#15 8.501 Execution halted
#15 8.530 FAILED
#15 8.532 Error: error testing if 'rjags' can be loaded [error code 1]
#15 8.533 Execution halted
```

This second example shows how an install-time package load can identify incompatible base system libraries.

<details>
<summary>Dockerfile.packrat-crosswired showing incompatible base libraries

```dockerfile
FROM rstudio/r-base:4.3-bionic AS base

RUN apt-get update && apt-get -y install pkg-config

ARG REPOSITORY=https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
RUN echo "options(repos = c(CRAN = '${REPOSITORY}'))" >> /opt/R/4.3.0/lib/R/etc/Rprofile.site

RUN R -s -e "install.packages('remotes')"

FROM base as setup

ARG PACKRAT_REF="aron-renv-binary-package-validation"
RUN R -s -e "remotes::install_github('rstudio/packrat', '${PACKRAT_REF}')"

FROM setup AS installation

RUN mkdir /content \
    && echo "library(fastmap)" > /content/script.R \
    && echo "options(download.file.method = 'curl', download.file.extra = paste('-s -L -f -A ', shQuote(getOption('HTTPUserAgent'))))" > /content/.Rprofile

WORKDIR /content

ENV RENV_INSTALL_TEST_LOAD=True

RUN R -s -e "packrat::init(enter = FALSE, infer.dependencies = FALSE)"
# install by R of fastmap into the packrat library..
RUN R -s -e "install.packages('fastmap')"
RUN R -s -e "packrat::snapshot()"
RUN rm -rf packrat/lib* packrat/src
# installation by packrat of fastmap into the packrat library using a BAD repository
ARG JAMMY_REPOSITORY=https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
RUN R -s -e "packrat::set_lockfile_metadata(repos = c(CRAN = '${JAMMY_REPOSITORY}'))"
RUN R -s -e "packrat::restore()"
RUN R -s -f "script.R"
```
</details>

```bash
docker build --progress=plain --no-cache-filter=setup -f Dockerfile.packrat-crosswired .
```

```
 > [installation 8/9] RUN R -s -e "packrat::restore()":
#17 2.259 /opt/R/4.3.0/lib/R/bin/R --vanilla -s -f '/tmp/Rtmpq1ZfQc/renv-install-75dce439a'
#17 2.259 ================================================================================
#17 2.259
#17 2.259 Error: package or namespace load failed for ‘fastmap’ in dyn.load(file, DLLpath = DLLpath, ...):
#17 2.259  unable to load shared object '/content/packrat/lib/x86_64-pc-linux-gnu/4.3.0/fastmap/libs/fastmap.so':
#17 2.259   /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /content/packrat/lib/x86_64-pc-linux-gnu/4.3.0/fastmap/libs/fastmap.so)
#17 2.259 Execution halted
#17 2.303 FAILED
#17 2.305 Error: error testing if 'fastmap' can be loaded [error code 1]
#17 2.305 Execution halted
```

### CODE REVIEW

File: R/restore.R [hunk 1]
```diff
@@ -584,6 +584,16 @@ installPkg <- function(pkgRecord,
       quiet <- isTRUE(packrat::opts$quiet.package.installation())
       install_local_path(path = pkgSrc, reload = FALSE,
                          dependencies = FALSE, quick = TRUE, quiet = quiet)
+      # if we just installed a binary package, check that it can be loaded
+      # (source packages are checked by default on install)
+      if (identical(pkgType, "binary")) {
+        status <- renv$catch(renv$renv_install_test(pkgRecord$name))
```
Comment (kevinushey) [inline R/restore.R:590]: We've made a change that ensures that the command output isn't automatically printed on error:

https://github.com/rstudio/renv/commit/3cbdd9109bd3eca116f306ae4edb60dff2783450

You might want to use `renv$abort()` instead of `stop()` below to ensure that message gets written to the console still.

**Review by kevinushey — APPROVED** [review]
LGTM!

File: R/restore.R (hunk 1 above)
Comment (aronatkins) [reply R/restore.R:590]: Took another renv update and used `renv$abort()`.

**Review by toph-allen — APPROVED** [review]

File: R/restore.R [hunk 2]
```diff
@@ -584,6 +584,16 @@ installPkg <- function(pkgRecord,
...
+        if (inherits(status, "error")) {
+          message("FAILED")
```
Comment (toph-allen) [inline R/restore.R:592]: Does this message look out of place in context? I.e. does it convey anything additional that `renv$abort` doesn't convey?

Comment (aronatkins) [reply R/restore.R:592]: Here is the full output from the `packrat::restore()` performed by the Docker build. The "FAILED" before `stop` is consistent with other exiting conditions throughout the restore.

Thoughts?

```
#15 [installation 7/8] RUN R -s -e "packrat::restore()"
#15 0.652 Installing coda (0.19-4) ...
#15 2.423 	OK (downloaded binary)
#15 2.423 Installing packrat (0.9.1-1) ...
#15 7.818 	OK (built source)
#15 7.819 Installing rjags (4-14) ...
#15 9.056 FAILED
#15 9.057 Error: error testing if 'rjags' can be loaded [error code 1]
#15 9.057 /opt/R/4.3.0/lib/R/bin/R --vanilla -s -f '/tmp/RtmpA18AdZ/renv-install-74536342'
#15 9.057 ================================================================================
#15 9.057
#15 9.057 Loading required package: coda
#15 9.057 Error: package or namespace load failed for ‘rjags’:
#15 9.057  .onLoad failed in loadNamespace() for 'rjags', details:
#15 9.057   call: dyn.load(file, DLLpath = DLLpath, ...)
#15 9.057   error: unable to load shared object '/content/packrat/lib/x86_64-pc-linux-gnu/4.3.0/rjags/libs/rjags.so':
#15 9.057   libjags.so.4: cannot open shared object file: No such file or directory
#15 9.057 Execution halted
#15 9.057
#15 9.057 Execution halted
#15 ERROR: process "/bin/sh -c R -s -e \"packrat::restore()\"" did not complete successfully: exit code: 1
```
