### PR TITLE
Bugfix/snapshot private GitHub packages

### LINKED ISSUE #442: Snapshot files with package installed from private GitHub repo
I have a project that includes a package `mypkg` installed from a private GitHub repo using `install_github(, auth_token = ...)`. The installation part seemed to work fine, but when trying to generate a snapshot later, the `src/mypkg` directory is empty and I get this error:

```
Fetching sources for mypkg (0.1.1) ... Error in snapshotSources(project, activeRepos(project), allRecordsFlat) : 
  Errors occurred when fetching source files:
Error in untar2(tarfile, files, list, exdir, restore_times) : 
  incomplete block on file
```

I tried manually generating a tarball and putting it in `src/mypkg`, but I get the same error. Is this just unsupported? Is there a workaround?

### PR DESCRIPTION
**Pull request by ras44**
resolves #442 and #447 by removing hard-coded `api.github.com` URL in download step.  Packages installed from private github repos are not located at api.github.com.  

Instead, this generates the url from the RemoteHost variable from the DESCRIPTION file, which should specify where the package was installed from.  The RemoteHost variable is also used to generate the protocol.  The protocol choice for users using `method='internal'`, has been removed, which could cause unwanted side-effects.

Rather than using `downloadWithRetries()`, which attempts to `inferAppropriateDownloadMethod`, and was leading to `method=libcurl`, which looks like it is not supported in `canUseLibCurlDownloadMethod`, we choose to use `githubDownload()`, since we know it is a github repo.

To work, the user must set the GITHUB_PAT environment variable:
```
#set GITHUB_PAT environment variable
Sys.setenv(GITHUB_PAT='<YOUR_GITHUB_PAT')
#confirm PAT is available with devtools:github_pat(), which is used by githubDownload(...)
devtools::github_pat() 
# before installing any other packages from github.com, user must unset GITHUB_PAT
Sys.unsetenv('GITHUB_PAT')
```

I've confirmed that this works for a test case with both an internal company package and an `github.com/rstats-db/DBI`.

### CODE REVIEW

File: R/restore.R [hunk 1]
```diff
@@ -202,22 +202,19 @@ getSourceForPkgRecord <- function(pkgRecord,
...
 
-    protocol <- if (identical(method, "internal"))
-      "http"
-    else
-      "https"
+    fmt <- "%s/repos/%s/%s/tarball/%s"
 
-    fmt <- "%s://api.github.com/repos/%s/%s/tarball/%s"
-    archiveUrl <- sprintf(fmt, protocol, pkgRecord$gh_username, pkgRecord$gh_repo, pkgRecord$gh_sha1)
+    archiveUrl <- sprintf(fmt, pkgRecord$remote_host, pkgRecord$gh_username, pkgRecord$gh_repo, pkgRecord$gh_sha1)
```
Comment (kevinushey) [inline R/restore.R]: The `remote_host` field was added with version v1.13.5 of devtools, if I'm understanding correctly:

https://github.com/rstudio/packrat/blob/3eb9c1250ae4384012164a75282f6992c4aa972e/R/github.R#L6

That was quite a while ago, but there's a chance there's still older R installations that don't have this version installed. Can we check to see if `pkgRecord$remote_host` is `NULL` or empty, and fallback to the GitHub API URL if it's not available?

**Comment by kevinushey** [comment]
This is what the lockfile entry looks like for Packrat when snapshotting on this branch:

```
Package: packrat
Source: github
Version: 0.4.8-1
GithubRepo: packrat
GithubUsername: ras44
GithubRef: bugfix/snapshot_private_github_packages
GithubSha1: 454c6c0e3ddd346c6511b645ede2e730318d5917
remote_host: https://api.github.com
remote_repo: packrat
remote_username: ras44
remote_ref: bugfix/snapshot_private_github_packages
remove_sha1: 454c6c0e3ddd346c6511b645ede2e730318d5917
Hash: 8899dbbe3edff321508a3685d1552764
```

Since we're only using the `remote_host` field, is it okay if we only keep that field? Otherwise we're duplicating a number of unneeded entries.

We also maintain a list of aliases here, for remapping of names:

https://github.com/rstudio/packrat/blob/3eb9c1250ae4384012164a75282f6992c4aa972e/R/lockfile.R#L266-L284

Can we add `remote_host` there as well?

**Comment by ras44** [comment]
@kevinushey I think I've resolved all the issues.  Let me know if I missed anything- thanks

**Comment by kevinushey** [comment]
Looks good! Thanks for taking the time to investigate the issue and submit the PR. I'm going to merge and then make some final tweaks.

**Comment by ras44** [comment]
Thanks, Kevin- glad to help!
