### PR TITLE
installPkg: do no work when using cached package and annotate safely

### LINKED ISSUE #720: packrat restore race condition
The use of packrat in Posit Connect can hit race-conditions during restore. It seems packrat directly writes to/reads from the DESCRIPTION file of packages and if two Connect apps are using the same package and are updated/redeployed at the same time, we could hit a race-condition where one or both updates fail. i.e.

```
2023/08/04 14:09:06.743139312 # Installing required R packages with `packrat::restore()` ---------------------
2023/08/04 14:09:07.220617061 Installing DBI (1.1.1) ... 
2023/08/04 14:09:07.245971037 Error in annotatePkgDesc(pkgRecord, project, lib): nrow(content) == 1 is not TRUE
2023/08/04 14:09:07.245980057 
2023/08/04 14:09:07.246015294 Unable to fully restore the R packages associated with this deployment.
2023/08/04 14:09:07.246019737 Please review the preceding messages to determine which package
2023/08/04 14:09:07.246055930 encountered installation difficulty and the cause of the failure.
2023/08/04 14:09:07.249423406 Warning message:
2023/08/04 14:09:07.249481533 In packrat::restore(overwrite.dirty = TRUE, prompt = FALSE, restart = FALSE) :
2023/08/04 14:09:07.249487850   The most recent snapshot was generated using R version 4.1.1
```
In this case a retry succeeded, so this was not an instance of a corrupt packrat cache.

This is especially fragile in a Connect instance with many git-backed deployments as multiple apps could be redeployed concurrently when Git.Concurrency>1.

### PR DESCRIPTION
**Pull request by aronatkins**
First, the `installPkg()` function no longer does additional work when the package was discovered in the cache. This avoids the most common situation where multiple processes performing package installation can race to the `annotatePkgDesc()` and `moveInstalledPackageToCache()` calls.

Second, `annotatePkgDesc()` writes its update to a temporary file before renaming to the target `DESCRIPTION`. This avoids a (now more rare) situation where a second process might see an incompletely written `DESCRIPTION` file.

As a side-effect, only the originally installing actor will annotate the `DESCRIPTION`. Previously, an update occurred even when the package was used from the cache, which overwrote an existing annotation.

Update: After thinking about this problem a bit more, realized that the root cause to #720 is because `annotatePkgDesc()` was previously writing into the package cache. After calling `restoreWithCopyFromCache()`, the library contains a symlink into the cache. Calling `annotatePkgDesc()` reads through the symlink and modifies the in-cache `DESCRIPTION`. This is why we saw multiple actors reading/writing the same file.

Fixes #720

### CODE REVIEW

File: R/restore.R [hunk 1]
```diff
@@ -391,16 +391,10 @@ annotatePkgDesc <- function(pkgRecord, project, lib = libDir(project)) {
...
-# Annotate a set of packages by name.
-annotatePkgs <- function(pkgNames, project, lib = libDir(project)) {
-  records <- searchPackages(lockInfo(project), pkgNames)
-  lapply(records, function(record) {
-    annotatePkgDesc(record, project, lib)
-  })
+  # Write it out using a temporary file so DESCRIPTION is never partial.
+  tmpf <- tempfile(tmpdir = dirname(descFile))
+  write_dcf(content, tmpf)
+  file.rename(tmpf, descFile)
```
Comment (kevinushey) [inline R/restore.R:397]: I believe this will emit a warning and return false on failure -- do we need to handle that scenario?

**Review by kevinushey — APPROVED** [review]

File: R/restore.R (hunk 1 above)
Comment (aronatkins) [reply R/restore.R:397]: You're right. I had dismissed the need to handle the error because the directory is known to be writable and we are not performing a cross-file-system move, but it's probably worth checking the return value.

**Review by toph-allen — APPROVED** [review]
No major comments from a code read. Questions that came up were answered elsewhere in the code.

One conceptual question: Do we know why the description was updated when installing from the cache? Are there any times where un-annotated descriptions can enter the cache (e.g. a package was installed via install.packages without Packrat) where we'd want to add the annotation? And if so, would the atomic updates (via renaming a temp file) be sufficient to fix the problem?

**Comment by kevinushey** [comment]
> Are there any times where un-annotated descriptions can enter the cache (e.g. a package was installed via install.packages without Packrat) where we'd want to add the annotation?

A long time ago, Packrat tried to distinguish between packages which were installed by Packrat itself, versus packages that were installed by the user. The intention here was to have a way of differentiating between packages that were "managed" or "known" to Packrat, and use that to customize the UI presented to the user in certain scenarios (e.g. helping them choose whether to snapshot or restore).

In practice, users found the behavior hard to understand, so that was phased out over time. I'm not sure if we still make use of the InstallAgent annotations anywhere in the Packrat sources, but if we do, it'd be nice to drop those once and for all.

File: R/restore.R [hunk 2]
```diff
@@ -598,35 +570,38 @@ installPkg <- function(pkgRecord,
   }
 
   # Annotate DESCRIPTION file so we know we installed it
-  annotatePkgDesc(pkgRecord, project, lib)
+  withCallingHandlers(
+    annotatePkgDesc(pkgRecord, project, lib),
+    error = function(e) {
+      unlink(pkgInstallPath, recursive = TRUE)
+      return(e)
```
Comment (kevinushey) [inline R/restore.R:577]: Nit: calling handlers don't alter control flow, so I believe the `return()` usage here is superfluous / ignored.

**Review by kevinushey — APPROVED** [review]

File: R/restore.R (hunk 2 above)
Comment (aronatkins) [reply R/restore.R]: Thanks. Confirmed that this is the case.

**Comment by aronatkins** [comment]
> I'm not sure if we still make use of the InstallAgent annotations anywhere in the Packrat sources

We do still use `InstallAgent`. See calls to `installedByPackrat()`.

**Comment by aronatkins** [comment]
> Are there any times where un-annotated descriptions can enter the cache (e.g. a package was installed via install.packages without Packrat) where we'd want to add the annotation? And if so, would the atomic updates (via renaming a temp file) be sufficient to fix the problem?

Users do not enroll packages in the cache; only Packrat performs cache additions and cache-uses while installing a package. I suppose it's possible that a user could add something to the Packrat library, but that is separate from cache management.
